name: SkyEntities
version: 1.1.0
author: DanMetzkr
api: 3.0.0
main: skycubes\skyentities\SkyEntities
description: SkyCubes custom entities
commands:
  se:
    description: Main Command
    usage: /se